name: Build LaTeX Document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crazydiamond75/latex-with-fonts:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: hpc_summary.tex
          latexmk_use_lualatex: true
          #args: -pvc
          #latexmk_shell_escape: true

      # May deploy to GitHub pages after this.

